language: node_js

node_js:
  - "10"

notifications:
  slack: jhonatanmedeiros:Qao51y7bLNTtBgO6ytrC7tXb

cache:
  yarn: true
  directories:
    - node_modules

env:
  - CI=true

script:
  - npm run lint
  - npm run test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API
  app: node-bank-account-api
  on:
    branch: master
    repo: JhonatanMedeiros/bank-account-api
